### ISSUE TITLE
Missing blocks

### ISSUE THREAD

**Issue by teozfrank** [lscardoso/gr-dsmx-rc#1]
Hello, 

I would be interested in testing this with GNU radio but there a several missing blocks to make the project function. Would it be possible to get the project in its entirety?

Kind Regards,
Frank.

**Comment by lscardoso** [comment]
Hi Frank

Which blocks are missing? Can you send me a python error message or screenshot of your GNURadio-companion flow graph?

Best regards,

Leonardo

**Comment by teozfrank** [comment]
Hi Leonardo,

I realised I was using a newer version of GNU Radio. I have now matched the version of the project and am using GNU radio 3.7.10 and I have solved some of the errors. See below the screenshot of the missing blocks and python error messages.

https://gyazo.com/77647f17636e5fb26574d56863797a01
https://gyazo.com/99a37523d2b37b751f14e0237f0ea832
https://gyazo.com/18778760ebf29305d2e6724cfcb4ef5c
https://gyazo.com/58945a30a686e4145f61ac7286c5c278
https://gyazo.com/905c2a8b873bb3cb4709c14eb9e138a2

Also I would like to mention I am using a HackRF which would use an osmocom source, is it compatible?

Kind Regards,
Frank.

**Comment by teozfrank** [comment]
Any update on this @lscardoso ?

**Comment by teozfrank** [comment]
Managed to get this to work build and run going to create another issue for that.
